version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: duckgame
      POSTGRES_USER: duckuser
      POSTGRES_PASSWORD: duckpass
    volumes:
      - /tmp/db_data:/var/lib/postgresql/data

  backend:
    image: kocew/duck-game-backend:latest
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  frontend:
    build: ./codechem-duck-game-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
