apiVersion: apps/v1
kind: Deployment
metadata:
  name: duck-game-frontend
  namespace: duck-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duck-game-frontend
  template:
    metadata:
      labels:
        app: duck-game-frontend
    spec:
      containers:
        - name: frontend
          image: kocew/duck-game-frontend:latest
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - containerPort: 80
