apiVersion: v1
kind: Service
metadata:
  name: duck-game-frontend
  namespace: duck-game
spec:
  selector:
    app: duck-game-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
